MDScreen:

    name: "getstarted"
    Image: 
        source: "asset/image.png"
        pos_hint: {"center_x":.5, "center_y":.65}

    Button:
        id: check
        text: "Get Started"
        size_hint: .66, .065
        pos_hint: {"center_x":.5, "center_y":.18}
        background_color: 0,0,0,0
        font_name: "BPoppins"
        on_release:
            root.manager.transition.direction = "left"
            root.manager.current = "signup"
        canvas.before:
            Color:
                rgb: rgba(0, 191, 255, 255)
            RoundedRectangle:
                size: self.size
                pos: self.pos
                radius: [5]
