MDScreen:
    name: "login"

    MDFloatLayout:
        md_bg_color:  1,1,1,1
        MDIconButton:
            icon: "arrow-left"
            pos_hint: {"center_y":.95}
            user_font_size:  "30sp"
            theme_text_color:  "Custom"
            text_color:  rgba(26,24,58,255)
            on_release: 
                root.manager.transition.direction: "right"
                root.manager.current = "signup"
        
        MDLabel:
            text: "W e l c o m e !"
            font_name: "BPoppins"
            font_size: "26sp"
            pos_hint: {"center_x":.6, "center_y":.85}
            color: rgba(0,0,59,255)
        
        MDLabel:
            text: "Sign in to continue"
            font_name: "BPoppins"
            font_size: "18sp"
            pos_hint: {"center_x":.6, "center_y":.79}
            color: rgba(135,133,193,255)
        
        MDFloatLayout:
            size_hint: .7,.07
            pos_hint: {"center_x":.5, "center_y":.63}
            TextInput:
                hint_text: "Email"
                font_name: "MPoppins"
                size_hint_y: .75
                pos_hint: {"center_x":.43, "center_y":.5}
                background_color: 1,1,1,0
                foreground_color: rgba(0,0,59,255)
                cursor_color: rgba(0,0,59,255)
                font_size: "14sp"
                cursor_width: "2sp"
                multiline: False
            MDFloatLayout:
                pos_hint: {"center_x":.45,"center_y":0}
                size_hint_y: .03
                md_bg_color: rgba(178,178,178,255)
        
        MDFloatLayout:
            size_hint: .7,.07
            pos_hint: {"center_x":.5, "center_y":.5}
            TextInput:
                hint_text: "Password"
                font_name: "MPoppins"
                size_hint_y: .75
                pos_hint: {"center_x":.43, "center_y":.5}
                background_color: 1,1,1,0
                foreground_color: rgba(0,0,59,255)
                cursor_color: rgba(0,0,59,255)
                font_size: "14sp"
                cursor_width: "2sp"
                multiline: False
                password: True
            MDFloatLayout:
                pos_hint: {"center_x":.45,"center_y":0}
                size_hint_y: .03
                md_bg_color: rgba(178,178,178,255)
        
        Button:
            text: "Login"
            size_hint: .66, .065
            pos_hint: {"center_x":.5,"center_y":.34}
            background_color: 0,0,0,0
            font_name: "BPoppins"
            on_release:
                root.manager.transition.direction = "left"
                root.manager.current = "main"
            canvas.before:
                Color:
                    rgb: rgba(0, 191, 255, 255)
                RoundedRectangle:
                    size: self.size
                    pos: self.pos
                    radius: [5]

        MDTextButton:
            text: "Forgot Password?"
            font_name: "BPoppins"
            font_size: "12sp"
            pos_hint: {"center_x":.5, "center_y":.28}
            color: rgba(68,78,132,255)

        MDLabel:
            text: "or"
            color: rgba(52,0,231,255)
            pos_hint: {"center_y": .22}
            font_name: "13sp"
            font_name: "BPoppins"
            halign: "center"
        
        MDFloatLayout:
            md_bg_color: rgba(178,178,178,255)
            size_hint: .3, .002
            pos_hint: {"center_x":.3, "center_y":.218}
        
        MDFloatLayout:
            md_bg_color: rgba(178,178,178,255)
            size_hint: .3, .002
            pos_hint: {"center_x":.7, "center_y":.218}
        
        MDLabel:
            text: "Social Media Login"
            font_name: "BPoppins"
            font_size: "13sp"
            halign: "center"
            pos_hint: {"center_y":.16}
            color: rgba(135,133,193,255)

        MDGridLayout:
            cols: 3
            size_hint: .6,.07
            pos_hint: {"center_x":.5, "center_y":.1}
            Image:
                source: "asset/logo1.png"
            Image:
                source: "asset/logo2.png"
            Image:
                source: "asset/logo3.png"
        
