MDScreen:
    name: "main"
    MDFloatLayout:
        md_bg_color: 1,1,1,1
        MDFloatLayout:
            size_hint: .7,.07
            pos_hint: {"center_x":.5, "center_y":.68}
            TextInput:
                hint_text: "Age"
                font_name: "MPoppins"
                size_hint_y: .75
                pos_hint: {"center_x":.43, "center_y":.5}
                background_color: 1,1,1,0
                foreground_color: rgba(0,0,59,255)
                cursor_color: rgba(0,0,59,255)
                font_size: "14sp"
                cursor_width: "2sp"
                multiline: False
            MDFloatLayout:
                pos_hint: {"center_x":.45,"center_y":0}
                size_hint_y: .03
                md_bg_color: rgba(178,178,178,255)


        MDFloatLayout:
            size_hint: .7,.07
            pos_hint: {"center_x":.5, "center_y":.56}
            TextInput:
                hint_text: "Height"
                font_name: "MPoppins"
                size_hint_y: .75
                pos_hint: {"center_x":.43, "center_y":.5}
                background_color: 1,1,1,0
                foreground_color: rgba(0,0,59,255)
                cursor_color: rgba(0,0,59,255)
                font_size: "14sp"
                cursor_width: "2sp"
                multiline: False
            MDFloatLayout:
                pos_hint: {"center_x":.45,"center_y":0}
                size_hint_y: .03
                md_bg_color: rgba(178,178,178,255)

        MDFloatLayout:
            size_hint: .7,.07
            pos_hint: {"center_x":.5, "center_y":.44}
            TextInput:
                hint_text: "Weight"
                font_name: "MPoppins"
                size_hint_y: .75
                pos_hint: {"center_x":.43, "center_y":.5}
                background_color: 1,1,1,0
                foreground_color: rgba(0,0,59,255)
                cursor_color: rgba(0,0,59,255)
                font_size: "14sp"
                cursor_width: "2sp"
                multiline: False
            MDFloatLayout:
                pos_hint: {"center_x":.45,"center_y":0}
                size_hint_y: .03
                md_bg_color: rgba(178,178,178,255)

        MDLabel:
            text: "Tell us a bit about yourself"
            font_name: "BPoppins"
            font_size: "16sp"
            pos_hint: {"center_x":.65, "center_y":.3}
            color: rgba(135,133,193,255)

        MDRectangleFlatButton:
            text: "Let's Go"
            color: rgba(0,0,59,255)
            halign: "center"
            pos_hint: {"center_x":.5, "center_y":.2}
            on_release:
                root.manager.transition.direction = "left"
                root.manager.current = "main_page"
